In [6]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
data = [[-1,2],[-0.5,6],[0,10],[1,18]]

# 数据归一化

In [3]:
ms = MinMaxScaler()
ms = ms.fit(data)
result = ms.transform(data)
result

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [4]:
ms.inverse_transform(result)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

# 数据标准化

In [10]:
ss = StandardScaler()
ss.fit(data)

StandardScaler()

In [11]:
ss.mean_

array([-0.125,  9.   ])

In [12]:
ss.var_

array([ 0.546875, 35.      ])

In [14]:
x_std = ss.transform(data)

In [15]:
x_std

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [16]:
x_std.mean()

0.0

In [18]:
ss.inverse_transform(x_std)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])